#!/usr/bin/env python3
"""Generate the reviewable inventory of custom Neovim behavior."""

from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "CUSTOMIZATIONS.md"
CONFIG_FILES = [ROOT / "init.lua", *sorted((ROOT / "lua/config").glob("*.lua"))]


def display(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def location(path: Path, offset: int) -> str:
    line = path.read_text().count("\n", 0, offset) + 1
    return f"`{display(path)}:{line}`"


def inventory() -> str:
    plugins: list[tuple[str, str]] = []
    options: list[tuple[str, str, str]] = []
    mappings: list[tuple[str, str, str, str]] = []
    autocmds: list[tuple[str, str]] = []

    for path in CONFIG_FILES:
        source = path.read_text()
        for match in re.finditer(r"\{\s*src\s*=\s*'https://github\.com/([^']+)'", source):
            plugins.append((match.group(1), location(path, match.start())))
        for match in re.finditer(r"(?m)^\s*vim\.(?:o|g|opt)\.([A-Za-z0-9_]+)\s*=\s*(?!=)([^\n]+)", source):
            value = match.group(2).split("--", 1)[0].strip()
            options.append((match.group(1), f"`{value}`", location(path, match.start())))
        for match in re.finditer(
            r"vim\.keymap\.set\(\s*(['\"])([^'\"]+)\1\s*,\s*(['\"])([^'\"]+)\3[\s\S]{0,500}?desc\s*=\s*(['\"])(.*?)\5",
            source,
        ):
            key = match.group(4)
            if not key.endswith('<leader>'):
                mappings.append((match.group(2), key, match.group(6), location(path, match.start())))
        for match in re.finditer(r"nvim_create_autocmd\(\s*('(?:[^']+)'|\{[^}]+\})\s*,", source):
            autocmds.append((match.group(1).strip(), location(path, match.start())))

    digests = [(display(path), hashlib.sha256(path.read_bytes()).hexdigest()) for path in CONFIG_FILES]
    rows = [
        "# Customization record",
        "",
        "> Generated by `make customizations`; do not edit by hand. CI regenerates this file",
        "> and fails when configuration changes are not recorded in the same PR.",
        "",
        "## Plugins",
        "",
        "| Repository | Declared at |",
        "| --- | --- |",
        *[f"| `{name}` | {where} |" for name, where in plugins],
        "",
        "## Editor and global settings",
        "",
        "| Setting | Configured value | Declared at |",
        "| --- | --- | --- |",
        *[f"| `{name}` | {value} | {where} |" for name, value, where in options],
        "",
        "## Keymaps",
        "",
        "Mappings with literal modes and keys are listed; generated mappings are exercised by their feature tests.",
        "",
        "| Mode | Key | Purpose | Declared at |",
        "| --- | --- | --- | --- |",
        *[f"| `{mode}` | `{key.replace('|', '&#124;')}` | {desc} | {where} |" for mode, key, desc, where in mappings],
        "",
        "## Automation",
        "",
        "| Event expression | Declared at |",
        "| --- | --- |",
        *[f"| `{event}` | {where} |" for event, where in autocmds],
        "",
        "## Behavioral coverage",
        "",
        "| Area | Executable record |",
        "| --- | --- |",
        "| Startup, options, global mappings, plugin availability, lint and Treesitter autocmds, AI clipboard formatting | `tests/config.lua` |",
        "| Explanation panes, exact selections, private notes, async request ordering and recovery | `tests/review_context.lua` |",
        "| Committed-diff ordering, marks, persistence, migration and assistant routing | `tests/review_route.lua` |",
        "| Tree/list rendering, nested marks, folding and navigation | `tests/review_tree.lua` |",
        "| Working tree, staged changes, native staging, invalidation and persistence | `tests/review_worktree.lua` |",
        "| Full-init integration with default-branch discovery and Diffview | `tests/review_startup.lua` |",
        "",
        "## Configuration fingerprints",
        "",
        "Any change to these files requires regenerating this record. This catches custom behavior that cannot be safely inferred from Lua syntax.",
        "",
        "| File | SHA-256 |",
        "| --- | --- |",
        *[f"| `{name}` | `{digest}` |" for name, digest in digests],
        "",
    ]
    return "\n".join(rows)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the committed record is stale")
    args = parser.parse_args()
    generated = inventory()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != generated:
            print("CUSTOMIZATIONS.md is stale; run `make customizations` and commit the result.")
            return 1
        print("Customization record is current.")
        return 0
    OUTPUT.write_text(generated)
    print(f"Updated {display(OUTPUT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
